version: '3.8'

services:
  bot:
    build: .
    container_name: kinozal_bot
    environment:
      # Telegram settings
      TG_TOKEN: "your-telegram-bot-token"
      BOT_ADMIN_ID: 'your-admin-id'
      BOT_ALLOWED_USERS: 'your-users-id'
      
      # Kinozal settings
      KZ_ADDR: "kinozal.tv"
      KZ_USER: "your-kinozal-username"
      KZ_PASS: "your-kinozal-password"
      
      # Transmission connection settings
      TRANS_ADDR: "transmission"
      TRANS_USER: "your-transmission-username"
      TRANS_PASS: "your-transmission-password"
      
      # Internal paths that match transmission's volume mappings
      FILMS_FOLDER: "/downloads/films"
      SERIES_FOLDER: "/downloads/series"
      AUDIOBOOKS_FOLDER: "/downloads/audiobooks"
    depends_on:
      - transmission
    restart: unless-stopped
    networks:
      - torrent-net

  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - USER=your-transmission-username
      - PASS=your-transmission-password
      - TRANSMISSION_WEB_HOME=/transmission/web
    ports:
      - "9091:9091"
    volumes:
      - /path/to/downloads:/downloads  # Main downloads directory
      - /path/to/config:/config       # Transmission configuration
    restart: unless-stopped
    networks:
      - torrent-net

networks:
  torrent-net:
    driver: bridge