name: Build and Release Binaries

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags, e.g., v1.0.0, v2.1.3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'  # Specify the Go version you want to use

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-modules-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-modules-
            
      - name: Install dependencies
        run: |
          cd src
          go mod tidy

      - name: Build binaries using Makefile
        run: |
          cd src
          make build-all

      - name: Archive and prepare binaries for release
        run: |
          # Create a release archive for Linux
          zip kinozal-bot-linux.zip src/kinozal-bot-linux .env.example README.md
          # Create a release archive for macOS
          zip kinozal-bot-darwin.zip src/kinozal-bot-darwin .env.example README.md
          # Create a release archive for Windows (using Linux zip)
          zip kinozal-bot-windows.zip src/kinozal-bot.exe .env.example README.md

      - name: Create a GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            kinozal-bot-linux.zip
            kinozal-bot-darwin.zip
            kinozal-bot-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}