name: Build and Release Docker Image

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-modules-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-modules-

      - name: Install dependencies
        run: |
          cd src
          go mod tidy

      - name: Build Go binary for Linux
        run: |
          cd src
          GOOS=linux GOARCH=amd64 go build -o kinozalbot-linux main.go

      - name: Build Docker image for Linux
        run: |
          # Ensure the binary is in the current directory
          ls -l src/kinozalbot-linux
          docker build -t ${{ secrets.DOCKER_USERNAME }}/kinozalbot:${GITHUB_SHA} -f src/Dockerfile src/

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/kinozalbot:${GITHUB_SHA}

      - name: Tag Docker image with 'latest'
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/kinozalbot:${GITHUB_SHA} ${{ secrets.DOCKER_USERNAME }}/kinozalbot:latest

      - name: Push 'latest' tag to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/kinozalbot:latest